# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8

RUST_MIN_VER="1.88.0"

CRATES="
	addr2line@0.25.1
	adler2@2.0.1
	aho-corasick@1.1.4
	android_system_properties@0.1.5
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	arc-swap@1.9.2
	async-compression@0.4.42
	async-recursion@1.1.1
	atomic-waker@1.1.2
	autocfg@1.5.1
	aws-lc-rs@1.17.1
	aws-lc-sys@0.42.0
	backtrace@0.3.76
	base64@0.22.1
	bitflags@2.13.0
	block-buffer@0.12.1
	bs58@0.5.1
	bstr@1.12.3
	bumpalo@3.20.3
	byteorder@1.5.0
	bytes@1.12.0
	cc@1.2.66
	cfb@0.7.3
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	chacha20@0.10.1
	chrono-tz-build@0.3.0
	chrono-tz@0.9.0
	chrono@0.4.45
	clap-sort@1.0.3
	clap@4.6.1
	clap_builder@4.6.0
	clap_derive@4.6.1
	clap_lex@1.1.0
	clap_usage@2.0.3
	clx@2.1.0
	cmake@0.1.58
	codegen@0.3.0
	color-eyre@0.6.5
	color-spantrace@0.3.0
	colorchoice@1.0.5
	combine@4.6.7
	compression-codecs@0.4.38
	compression-core@0.4.32
	console@0.16.4
	const-oid@0.10.2
	core-foundation-sys@0.8.7
	core-foundation@0.10.1
	cpufeatures@0.3.0
	crc32fast@1.5.0
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.21
	crypto-common@0.2.2
	darling@0.23.0
	darling_core@0.23.0
	darling_macro@0.23.0
	dashmap@6.2.1
	demand@2.0.2
	deranged@0.5.8
	deunicode@1.6.2
	digest@0.11.3
	dirs-sys@0.5.0
	dirs@6.0.0
	displaydoc@0.2.6
	duct@1.1.1
	dunce@1.0.5
	dyn-clone@1.0.20
	either@1.16.0
	encode_unicode@1.0.0
	ensembler@1.1.2
	equivalent@1.0.2
	errno@0.3.14
	expr-lang@1.1.1
	eyre@0.6.12
	fastrand@2.4.1
	filetime@0.2.29
	find-msvc-tools@0.1.9
	flate2@1.1.9
	fnv@1.0.7
	form_urlencoded@1.2.2
	fs_extra@1.3.0
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-sink@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	fuzzy-matcher@0.3.7
	getrandom@0.2.17
	getrandom@0.4.3
	gimli@0.32.3
	git2@0.21.0
	globset@0.4.18
	globwalk@0.9.1
	hashbrown@0.12.3
	hashbrown@0.14.5
	hashbrown@0.17.1
	heck@0.5.0
	hex@0.4.3
	homedir@0.3.6
	http-body-util@0.1.3
	http-body@1.0.1
	http@1.4.2
	httparse@1.10.1
	humansize@2.1.3
	hybrid-array@0.4.13
	hyper-rustls@0.27.9
	hyper-util@0.1.20
	hyper@1.10.1
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.65
	icu_collections@2.2.0
	icu_locale_core@2.2.0
	icu_normalizer@2.2.0
	icu_normalizer_data@2.2.0
	icu_properties@2.2.0
	icu_properties_data@2.2.0
	icu_provider@2.2.0
	ident_case@1.0.1
	idna@1.1.0
	idna_adapter@1.2.2
	ignore@0.4.27
	indenter@0.3.4
	indexmap@1.9.3
	indexmap@2.14.0
	indicatif@0.18.6
	infer@0.19.0
	ipnet@2.12.0
	is_ci@1.2.0
	is_terminal_polyfill@1.70.2
	itertools@0.14.0
	itertools@0.15.0
	itoa@1.0.18
	jni-macros@0.22.4
	jni-sys-macros@0.4.1
	jni-sys@0.4.1
	jni@0.22.4
	jobserver@0.1.35
	js-sys@0.3.103
	kdl@6.5.0
	lazy_static@1.5.0
	libc@0.2.186
	libgit2-sys@0.18.5+1.9.4
	libm@0.2.16
	libredox@0.1.18
	libz-sys@1.1.29
	linux-raw-sys@0.12.1
	litemap@0.8.2
	lock_api@0.4.14
	log@0.4.33
	lru-slab@0.1.2
	matchers@0.2.0
	memchr@2.8.2
	miette-derive@7.6.0
	miette@7.6.0
	miniz_oxide@0.8.9
	mio@1.2.1
	nix@0.30.1
	nix@0.31.3
	nom@8.0.0
	nu-ansi-term@0.50.3
	num-bigint@0.4.8
	num-complex@0.4.6
	num-conv@0.2.2
	num-integer@0.1.46
	num-iter@0.1.45
	num-rational@0.4.2
	num-traits@0.2.19
	num@0.4.3
	object@0.37.3
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	openssl-probe@0.2.1
	option-ext@0.2.0
	os_pipe@1.2.3
	owo-colors@4.3.0
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	parse-zoneinfo@0.3.1
	percent-encoding@2.3.2
	pest@2.8.7
	pest_derive@2.8.7
	pest_generator@2.8.7
	pest_meta@2.8.7
	phf@0.11.3
	phf_codegen@0.11.3
	phf_generator@0.11.3
	phf_shared@0.11.3
	pin-project-lite@0.2.17
	pkg-config@0.3.33
	pklr@1.1.2
	portable-atomic@1.13.1
	potential_utf@0.1.5
	powerfmt@0.2.0
	ppv-lite86@0.2.21
	proc-macro2@1.0.106
	quinn-proto@0.11.16
	quinn-udp@0.5.15
	quinn@0.11.11
	quote@1.0.46
	r-efi@6.0.0
	rand@0.10.2
	rand@0.8.6
	rand_chacha@0.3.1
	rand_core@0.10.1
	rand_core@0.6.4
	rand_pcg@0.10.2
	redox_syscall@0.5.18
	redox_users@0.5.2
	ref-cast-impl@1.0.25
	ref-cast@1.0.25
	regex-automata@0.4.14
	regex-syntax@0.8.11
	regex@1.12.4
	reqwest@0.13.4
	ring@0.17.14
	roff@0.2.2
	rustc-demangle@0.1.27
	rustc-hash@2.1.3
	rustc_version@0.4.1
	rustix@1.1.4
	rustls-native-certs@0.8.4
	rustls-pki-types@1.15.0
	rustls-platform-verifier-android@0.1.1
	rustls-platform-verifier@0.7.0
	rustls-webpki@0.103.13
	rustls@0.23.41
	rustversion@1.0.22
	ryu@1.0.23
	same-file@1.0.6
	schannel@0.1.29
	schemars@0.9.0
	schemars@1.2.1
	scopeguard@1.2.0
	security-framework-sys@2.17.0
	security-framework@3.7.0
	semver@1.0.28
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	serde_spanned@1.1.1
	serde_urlencoded@0.7.1
	serde_with@3.21.0
	serde_with_macros@3.21.0
	serde_yaml@0.9.34+deprecated
	sha2@0.11.0
	sharded-slab@0.1.7
	shared_child@1.1.1
	shared_thread@0.2.0
	shell-quote@0.7.2
	shell-words@1.1.1
	shlex@2.0.1
	sigchld@0.2.4
	signal-hook-registry@1.4.8
	signal-hook@0.3.18
	signal-hook@0.4.4
	simd-adler32@0.3.9
	simd_cesu8@1.1.1
	simdutf8@0.1.5
	similar@3.1.1
	siphasher@1.0.3
	slab@0.4.12
	slug@0.1.6
	smallvec@1.15.2
	socket2@0.6.4
	stable_deref_trait@1.2.1
	strsim@0.11.1
	strum@0.27.2
	strum@0.28.0
	strum_macros@0.27.2
	strum_macros@0.28.0
	subtle@2.6.1
	syn@2.0.118
	sync_wrapper@1.0.2
	synstructure@0.13.2
	tempfile@3.27.0
	tera@1.20.1
	tera@2.0.0
	termcolor@1.4.1
	terminal_size@0.4.4
	thiserror-impl@2.0.18
	thiserror@2.0.18
	thread_local@1.1.9
	time-core@0.1.9
	time-macros@0.2.31
	time@0.3.53
	tinystr@0.8.3
	tinyvec@1.11.0
	tinyvec_macros@0.1.1
	tokio-macros@2.7.0
	tokio-rustls@0.26.4
	tokio-util@0.7.18
	tokio@1.52.3
	toml@1.1.2+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_parser@1.1.2+spec-1.1.0
	toml_writer@1.1.1+spec-1.1.0
	tower-http@0.6.11
	tower-layer@0.3.3
	tower-service@0.3.3
	tower@0.5.3
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-error@0.2.1
	tracing-log@0.2.0
	tracing-serde@0.2.0
	tracing-subscriber@0.3.23
	tracing@0.1.44
	try-lock@0.2.5
	typed-path@0.12.3
	typenum@1.20.1
	ucd-trie@0.1.7
	unicode-ident@1.0.24
	unicode-segmentation@1.13.3
	unicode-width@0.1.14
	unicode-width@0.2.2
	unit-prefix@0.5.2
	unsafe-libyaml@0.2.11
	untrusted@0.9.0
	url@2.5.8
	usage-lib@2.18.2
	utf8_iter@1.0.4
	utf8parse@0.2.2
	uuid@1.23.4
	valuable@0.1.1
	vcpkg@0.2.15
	versions@7.0.0
	walkdir@2.5.0
	want@0.3.1
	wasi@0.11.1+wasi-snapshot-preview1
	wasm-bindgen-futures@0.4.76
	wasm-bindgen-macro-support@0.2.126
	wasm-bindgen-macro@0.2.126
	wasm-bindgen-shared@0.2.126
	wasm-bindgen@0.2.126
	web-sys@0.3.103
	web-time@1.1.0
	webpki-root-certs@1.0.8
	widestring@1.2.1
	winapi-util@0.1.11
	windows-collections@0.2.0
	windows-core@0.61.2
	windows-core@0.62.2
	windows-future@0.2.1
	windows-implement@0.60.2
	windows-interface@0.59.3
	windows-link@0.1.3
	windows-link@0.2.1
	windows-numerics@0.2.0
	windows-result@0.3.4
	windows-result@0.4.1
	windows-strings@0.4.2
	windows-strings@0.5.1
	windows-sys@0.52.0
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows-targets@0.53.5
	windows-threading@0.1.0
	windows@0.61.3
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@0.6.24
	winnow@1.0.3
	writeable@0.6.3
	xx@2.6.1
	yoke-derive@0.8.2
	yoke@0.8.3
	zerocopy-derive@0.8.52
	zerocopy@0.8.52
	zerofrom-derive@0.1.7
	zerofrom@0.1.8
	zeroize@1.9.0
	zerotrie@0.2.4
	zerovec-derive@0.11.3
	zerovec@0.11.6
	zip@8.6.0
	zlib-rs@0.6.5
	zmij@1.0.21
	zopfli@0.8.3
"

inherit cargo shell-completion

DESCRIPTION="Git hook manager and project linting tool"
HOMEPAGE="https://hk.jdx.dev https://github.com/jdx/hk"
SRC_URI="
	https://github.com/jdx/hk/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64 ~arm64"
IUSE="bash-completion fish-completion zsh-completion"

DEPEND="sys-libs/zlib"
RDEPEND="
	${DEPEND}
	dev-vcs/git
	bash-completion? ( dev-util/usage )
	fish-completion? ( dev-util/usage )
	zsh-completion? ( dev-util/usage )
"
BDEPEND="
	dev-build/cmake
	virtual/pkgconfig
	bash-completion? ( dev-util/usage )
	fish-completion? ( dev-util/usage )
	zsh-completion? ( dev-util/usage )
"

# rust does not use *FLAGS from make.conf, silence portage warning
QA_FLAGS_IGNORED="usr/bin/hk"

src_configure() {
	# Skip the generate-docs helper binary
	cargo_src_configure --bin hk
}

src_install() {
	cargo_src_install
	dodoc README.md CHANGELOG.md

	# Completions are generated via the external usage CLI (jdx/usage).
	# Put the just-installed hk on PATH for --usage-cmd.
	local -x PATH="${ED}/usr/bin:${PATH}"

	if use bash-completion; then
		usage g completion bash hk --usage-cmd "hk usage" > hk.bash ||
			die 'Unable to generate bash completions'
		newbashcomp hk.bash hk
	fi
	if use fish-completion; then
		usage g completion fish hk --usage-cmd "hk usage" > hk.fish ||
			die 'Unable to generate fish completions'
		newfishcomp hk.fish hk.fish
	fi
	if use zsh-completion; then
		usage g completion zsh hk --usage-cmd "hk usage" > hk.zsh ||
			die 'Unable to generate zsh completions'
		newzshcomp hk.zsh _hk
	fi
}
