# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8

# kdl@6.7.1 requires rust-version 1.95
RUST_MIN_VER="1.95.0"

CRATES="
	addr2line@0.25.1
	adler2@2.0.1
	aho-corasick@1.1.4
	alloca@0.4.0
	android_system_properties@0.1.5
	anes@0.1.6
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	assert_cmd@2.2.2
	autocfg@1.5.1
	backtrace-ext@0.2.1
	backtrace@0.3.76
	base64@0.22.1
	bitflags@1.3.2
	bitflags@2.13.0
	bs58@0.5.1
	bstr@1.12.3
	bumpalo@3.20.3
	cast@0.3.0
	cc@1.2.66
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	chacha20@0.10.1
	chrono@0.4.45
	ciborium-io@0.2.2
	ciborium-ll@0.2.2
	ciborium@0.2.2
	clap-sort@1.0.3
	clap@4.6.1
	clap_builder@4.6.0
	clap_derive@4.6.1
	clap_lex@1.1.0
	colorchoice@1.0.5
	console@0.16.4
	core-foundation-sys@0.8.7
	cpufeatures@0.3.0
	criterion-plot@0.8.2
	criterion@0.8.2
	crossbeam-deque@0.8.7
	crossbeam-epoch@0.9.20
	crossbeam-utils@0.8.22
	crunchy@0.2.4
	ctor@1.0.8
	darling@0.23.0
	darling_core@0.23.0
	darling_macro@0.23.0
	defmt-macros@1.1.1
	defmt-parser@1.0.0
	defmt@1.1.1
	deranged@0.5.8
	diff@0.1.13
	difflib@0.4.0
	duct@1.1.1
	dyn-clone@1.0.20
	either@1.16.0
	encode_unicode@1.0.0
	env_filter@2.0.0
	env_logger@0.11.11
	equivalent@1.0.2
	errno-dragonfly@0.1.2
	errno@0.2.8
	errno@0.3.14
	exec@0.3.1
	fastrand@2.4.1
	filetime@0.2.29
	find-msvc-tools@0.1.9
	float-cmp@0.10.0
	futures-core@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	getrandom@0.4.3
	gimli@0.32.3
	half@2.7.1
	hashbrown@0.12.3
	hashbrown@0.17.1
	heck@0.5.0
	hex@0.4.3
	homedir@0.3.6
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.65
	ident_case@1.0.1
	indexmap@1.9.3
	indexmap@2.14.0
	insta@1.48.0
	is_ci@1.2.0
	is_terminal_polyfill@1.70.2
	itertools@0.13.0
	itertools@0.14.0
	itertools@0.15.0
	itoa@1.0.18
	jiff-static@0.2.31
	jiff@0.2.31
	js-sys@0.3.103
	kdl@6.7.1
	libc@0.2.186
	link-section@0.19.0
	linktime-proc-macro@0.2.0
	linux-raw-sys@0.12.1
	log@0.4.33
	memchr@2.8.2
	miette-derive@7.6.0
	miette@7.6.0
	miniz_oxide@0.8.9
	nix@0.30.1
	nom@8.0.0
	normalize-line-endings@0.3.0
	num-conv@0.2.2
	num-traits@0.2.19
	object@0.37.3
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	oorandom@11.1.5
	os_pipe@1.2.3
	owo-colors@4.3.0
	page_size@0.6.0
	pin-project-lite@0.2.17
	plotters-backend@0.3.7
	plotters-svg@0.3.7
	plotters@0.3.7
	portable-atomic-util@0.2.7
	portable-atomic@1.13.1
	powerfmt@0.2.0
	predicates-core@1.0.10
	predicates-tree@1.0.13
	predicates@3.1.4
	pretty_assertions@1.4.1
	proc-macro2@1.0.106
	quote@1.0.46
	r-efi@6.0.0
	rand@0.10.2
	rand_core@0.10.1
	rayon-core@1.13.0
	rayon@1.12.0
	ref-cast-impl@1.0.25
	ref-cast@1.0.25
	regex-automata@0.4.14
	regex-syntax@0.8.11
	regex@1.12.4
	roff@1.1.1
	rustc-demangle@0.1.27
	rustix@1.1.4
	rustversion@1.0.22
	same-file@1.0.6
	schemars@0.9.0
	schemars@1.2.1
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	serde_with@3.21.0
	serde_with_macros@3.21.0
	shared_child@1.1.1
	shared_thread@0.2.0
	shell-words@1.1.1
	shlex@2.0.1
	sigchld@0.2.4
	signal-hook-registry@1.4.8
	signal-hook@0.3.18
	similar@2.7.0
	slab@0.4.12
	strsim@0.11.1
	strum@0.28.0
	strum_macros@0.28.0
	supports-color@3.0.2
	supports-hyperlinks@3.2.0
	supports-unicode@3.0.0
	syn@2.0.118
	tempfile@3.27.0
	tera@2.0.0
	terminal_size@0.4.4
	termtree@0.5.1
	textwrap@0.16.2
	thiserror-impl@2.0.18
	thiserror@2.0.18
	time-core@0.1.9
	time-macros@0.2.31
	time@0.3.53
	tinytemplate@1.2.1
	tinyvec@1.11.0
	tinyvec_macros@0.1.1
	unicode-ident@1.0.24
	unicode-linebreak@0.1.5
	unicode-width@0.1.14
	unicode-width@0.2.2
	utf8parse@0.2.2
	versions@7.0.0
	wait-timeout@0.2.1
	walkdir@2.5.0
	wasm-bindgen-macro-support@0.2.126
	wasm-bindgen-macro@0.2.126
	wasm-bindgen-shared@0.2.126
	wasm-bindgen@0.2.126
	web-sys@0.3.103
	widestring@1.2.1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-collections@0.2.0
	windows-core@0.61.2
	windows-core@0.62.2
	windows-future@0.2.1
	windows-implement@0.60.2
	windows-interface@0.59.3
	windows-link@0.1.3
	windows-link@0.2.1
	windows-numerics@0.2.0
	windows-result@0.3.4
	windows-result@0.4.1
	windows-strings@0.4.2
	windows-strings@0.5.1
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.53.5
	windows-threading@0.1.0
	windows@0.61.3
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.53.1
	winnow@0.7.15
	xx@2.6.1
	yansi@1.0.1
	zerocopy-derive@0.8.53
	zerocopy@0.8.53
	zmij@1.0.21
"

inherit cargo shell-completion

DESCRIPTION="Spec and CLI for defining CLI tools (completions, docs, man pages)"
HOMEPAGE="https://usage.jdx.dev https://github.com/jdx/usage"
SRC_URI="
	https://github.com/jdx/usage/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 ISC MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64 ~arm64"
IUSE="bash-completion fish-completion zsh-completion"

# rust does not use *FLAGS from make.conf, silence portage warning
QA_FLAGS_IGNORED="usr/bin/usage"

src_install() {
	cargo_src_install --path cli
	dodoc README.md CHANGELOG.md
	doman cli/assets/usage.1

	use bash-completion &&
		newbashcomp cli/assets/completions/usage.bash usage
	use fish-completion &&
		newfishcomp cli/assets/completions/usage.fish usage.fish
	use zsh-completion &&
		newzshcomp cli/assets/completions/_usage _usage
}
